version: '3.6'
services:

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb-vol:/data/db
      - ./db-init/mongo:/docker-entrypoint-initdb.d/
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=g5
      - MONGO_INITDB_ROOT_PASSWORD=g5
      - MONGO_INITDB_DATABASE=repairs
    ports:
      - 27017:27017
volumes:
  mongodb-vol:
    name: mongo-vol
